# Generated by Django 5.0 on 2023-12-30 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=30, unique=True)),
                ('firstName', models.CharField(blank=True, max_length=50, null=True)),
                ('lastName', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('tura1', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='tura1', to='scheduler.medic', to_field='nickname')),
                ('tura2', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='tura2', to='scheduler.medic', to_field='nickname')),
                ('tura3', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='tura3', to='scheduler.medic', to_field='nickname')),
            ],
        ),
    ]
