# Generated by Django 5.0 on 2023-12-30 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduler',
            name='tura1',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tura1', to='scheduler.medic', to_field='nickname'),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='tura2',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tura2', to='scheduler.medic', to_field='nickname'),
        ),
        migrations.AlterField(
            model_name='scheduler',
            name='tura3',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tura3', to='scheduler.medic', to_field='nickname'),
        ),
    ]
